version: "3.8"

services: 
    mongo:
        container_name: mongo
        ports: 
            - 27017:27017
        image: mongo:4.4.5-bionic
        volumes: 
            - db_data:/data/db
        networks: 
            - node_network
    node:
        container_name: node
        ports: 
            - 8080:8080
        image: node
        networks: 
            - node_network
        depends_on:
            - mongo
        environment: 
            - NAME=belajar=mongo
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
networks: 
    node_network:
        name: program_network
volumes: 
    db_data:
        name: db_data